services:
  nginx:
    build:
      context: .
    ports:
      - "5173:80"
    volumes:
      - ../dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

#docker compose -p scm-frontend-nginx up -d
