version: "3.9"
services:
 frontend:
   build:
     context: ./scm-frontend
     dockerfile: Dockerfile
   container_name: scm-frontend
   restart: always
   ports:
     - 5173:5173
   volumes:
     - ./scm-frontend:/app
     - /app/node_modules
   env_file:
     - .env
   environment:
     - VITE_APP_BACKEND_ADDRESS=localhost:8080/api/v1
   networks:
     - network
networks:
 network: